import logging
import requests
from config.settings import TELEGRAM_BOT_TOKEN, TELEGRAM_CHAT_ID
from typing import Dict, Any

logger = logging.getLogger(__name__)

class TelegramNotifier:
    def __init__(self):
        self.bot_token = TELEGRAM_BOT_TOKEN
        self.chat_id = TELEGRAM_CHAT_ID
    
    def send_alert(self, ticker: str, signal_data: Dict[str, Any], trade_plan: Dict[str, Any], analysis: str):
        """
        Send a formatted alert to Telegram.
        """
        if not self.bot_token or not self.chat_id:
            logger.warning("Telegram Token or Chat ID missing. Skipping alert.")
            return

        message = self._format_message(ticker, signal_data, trade_plan, analysis)
        
        url = f"https://api.telegram.org/bot{self.bot_token}/sendMessage"
        payload = {
            "chat_id": self.chat_id,
            "text": message,
            "parse_mode": "Markdown"
        }
        
        try:
            response = requests.post(url, json=payload, timeout=10)
            response.raise_for_status()
            logger.info(f"Telegram Alert sent for {ticker}")
        except Exception as e:
            logger.error(f"Failed to send Telegram alert: {e}")

    def _format_message(self, ticker: str, signal_data: Dict[str, Any], trade_plan: Dict[str, Any], analysis: str) -> str:
        # Extract signal keys that are true
        signals = [k.replace('_', ' ').title() for k, v in signal_data.get('signals', {}).items() if v]
        signal_str = ", ".join(signals)
        
        return f"""
🤖 *Saftrade Alert*
**#{ticker}** (Valid Setup)

📊 *Signals:* {signal_str}
Close: {signal_data.get('close', 0)}

🧠 *AI Analysis:*
"{analysis}"

📉 *Trade Plan:*
* Entry: {trade_plan.get('entry')}
* SL: {trade_plan.get('stop_loss')}
* TP: {trade_plan.get('take_profit')}
* R:R: {trade_plan.get('risk_reward', 'N/A')}

_Generated by Saftrade_
"""
